# Generated by Django 3.2.8 on 2021-10-26 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('link', models.IntegerField(choices=[(1, 'Pai de Aluno'), (2, 'Professor'), (3, 'Funcionário'), (4, 'Outro')], default=1)),
                ('link_school', models.TextField(blank=True, default='')),
                ('total', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
                ('can_change', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('alergies', models.TextField(blank=True, default='', max_length=100)),
                ('obs', models.TextField(blank=True, default='', max_length=100)),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('kids_menu', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
