# Generated by Django 3.2.8 on 2021-10-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='link',
            field=models.IntegerField(choices=[(1, 'Aluno'), (2, 'Parente de Aluno'), (3, 'Professor'), (4, 'Coordenação'), (5, 'Outro')], default=1),
        ),
    ]
