# Generated by Django 3.2.8 on 2021-11-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_userprofile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='day',
            field=models.CharField(default='10/11/2021', max_length=30),
        ),
    ]
