# Generated by Django 3.2.8 on 2021-11-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='day',
        ),
    ]
